---
directory: /home/tcomi/projects/abwolf_abc/msprime_scripts/snakefiles
cluster-config: /home/tcomi/projects/abwolf_abc/msprime_scripts/snakefiles/della_cluster.yaml
snakefile: /home/tcomi/projects/abwolf_abc/msprime_scripts/snakefiles/Snakefile
cluster: "sbatch --cpus-per-task={cluster.n} --mem={cluster.memory} \
          --time={cluster.time} --output=slurm_out/%x_%A \
          --job-name={cluster.jobname} --parsable"

use-conda: true
max-jobs-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 50
nolock: false
quiet: false
